In [2]:
import pandas as pd
from IPython.display import display

data = {
    "Student_ID": [101, 102, 103, 104, 105, 102, 106, 104],
    "Name": ["Rahul", "Ananya", "Arjun", "Priya", "Kiran", "Ananya", "Sneha", "Priya"],
    "Department": ["CSE", "ISE", "CSE", "ECE", "AIML", "ISE", "CSE", "ECE"],
    "Marks": [92, 85, 76, 88, 67, 85, 95, 88]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

print("Rows before cleaning:", len(df))

duplicates = df[df.duplicated()]
print("\nDuplicate Records:")
display(duplicates)

print("Number of duplicate records:", df.duplicated().sum())

cleaned_df = df.drop_duplicates().reset_index(drop=True)

print("\nCleaned Dataset:")
display(cleaned_df)

print("\nRows after cleaning:", len(cleaned_df))
print("Rows removed:", len(df) - len(cleaned_df))
print("Duplicates remaining:", cleaned_df.duplicated().sum())

Original Dataset:

   Student_ID    Name Department  Marks
0         101   Rahul        CSE     92
1         102  Ananya        ISE     85
2         103   Arjun        CSE     76
3         104   Priya        ECE     88
4         105   Kiran       AIML     67
5         102  Ananya        ISE     85
6         106   Sneha        CSE     95
7         104   Priya        ECE     88

Rows before cleaning: 8

Duplicate Records:

   Student_ID    Name Department  Marks
5         102  Ananya        ISE     85
7         104   Priya        ECE     88

Number of duplicate records: 2

Cleaned Dataset:

   Student_ID    Name Department  Marks
0         101   Rahul        CSE     92
1         102  Ananya        ISE     85
2         103   Arjun        CSE     76
3         104   Priya        ECE     88
4         105   Kiran       AIML     67
5         106   Sneha        CSE     95

Rows after cleaning: 6
Rows removed: 2
Duplicates remaining: 0