In [3]:
import pandas as pd

# Load the Iris dataset
df = pd.read_csv("../Veda_Internship_Day16/iris.csv")

print("Original Dataset:")
display(df.head())

# Example 1: Sepal length greater than 5
condition1 = df[df["sepal_length"] > 5]
print("\n1. Sepal length greater than 5:")
display(condition1.head())
print("Number of records:", len(condition1))

# Example 2: Petal length greater than 4
condition2 = df[df["petal_length"] > 4]
print("\n2. Petal length greater than 4:")
display(condition2.head())
print("Number of records:", len(condition2))

# Example 3: Apply two conditions using AND
condition3 = df[
    (df["sepal_length"] > 5) &
    (df["petal_length"] > 4)
]
print("\n3. Sepal length > 5 AND petal length > 4:")
display(condition3.head())
print("Number of records:", len(condition3))

# Example 4: Filter setosa flowers
condition4 = df[df["species"] == "setosa"]
print("\n4. Setosa flowers:")
display(condition4.head())
print("Number of records:", len(condition4))

Original Dataset:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

1. Sepal length greater than 5:

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa

Number of records: 118

2. Petal length greater than 4:

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor

Number of records: 84

3. Sepal length > 5 AND petal length > 4:

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor

Number of records: 83

4. Setosa flowers:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Number of records: 50