In [1]:
import pandas as pd
from IPython.display import display

In [2]:
data = {
    "Hours_Studied": [2, 3, 4, 5, 6, 7, 8, 9, 1, 10],
    "Attendance": [60, 65, 70, 75, 80, 85, 90, 95, 50, 98],
    "Previous_Score": [35, 40, 45, 50, 55, 65, 70, 75, 30, 85],
    "Final_Marks": [38, 43, 48, 55, 62, 70, 78, 85, 32, 92]
}

df = pd.DataFrame(data)

print("Student Performance Dataset:")
display(df)

Student Performance Dataset:

   Hours_Studied  Attendance  Previous_Score  Final_Marks
0              2          60              35           38
1              3          65              40           43
2              4          70              45           48
3              5          75              50           55
4              6          80              55           62
5              7          85              65           70
6              8          90              70           78
7              9          95              75           85
8              1          50              30           32
9             10          98              85           92

In [3]:
X = df[["Hours_Studied", "Attendance", "Previous_Score"]]

print("Selected Features (X):")
display(X)

Selected Features (X):

   Hours_Studied  Attendance  Previous_Score
0              2          60              35
1              3          65              40
2              4          70              45
3              5          75              50
4              6          80              55
5              7          85              65
6              8          90              70
7              9          95              75
8              1          50              30
9             10          98              85

In [4]:
y = df["Final_Marks"]

print("Selected Target (y):")
display(y)

Selected Target (y):

0    38
1    43
2    48
3    55
4    62
5    70
6    78
7    85
8    32
9    92
Name: Final_Marks, dtype: int64

In [5]:
print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nFeature Columns:")
print(X.columns.tolist())

print("\nTarget Column:")
print(y.name)

print("\nMissing Values in Features:")
print(X.isnull().sum())

print("\nMissing Values in Target:")
print(y.isnull().sum())

Feature Shape: (10, 3)
Target Shape: (10,)

Feature Columns:
['Hours_Studied', 'Attendance', 'Previous_Score']

Target Column:
Final_Marks

Missing Values in Features:
Hours_Studied     0
Attendance        0
Previous_Score    0
dtype: int64

Missing Values in Target:
0

In [6]:
print("FEATURE AND TARGET SELECTION")
print("--------------------------------")

print("Features (X):")
print("1. Hours_Studied")
print("2. Attendance")
print("3. Previous_Score")

print("\nTarget (y):")
print("Final_Marks")

print("\nReason for Selection:")
print("1. Study hours may help explain student performance.")
print("2. Attendance may provide useful information about participation.")
print("3. Previous scores may help estimate future performance.")
print("4. Final marks are the value the model will attempt to predict.")
print("5. The target column is kept separate from the input features.")

FEATURE AND TARGET SELECTION
--------------------------------
Features (X):
1. Hours_Studied
2. Attendance
3. Previous_Score

Target (y):
Final_Marks

Reason for Selection:
1. Study hours may help explain student performance.
2. Attendance may provide useful information about participation.
3. Previous scores may help estimate future performance.
4. Final marks are the value the model will attempt to predict.
5. The target column is kept separate from the input features.