In [2]:
import pandas as pd

# Load the Iris dataset
df = pd.read_csv("../Veda_Internship_Day16/iris.csv")

print("Original Dataset:")
display(df.head())

# 1. Sort by sepal length in ascending order
print("\n1. Sepal Length - Ascending Order:")
ascending = df.sort_values(by="sepal_length", ascending=True)
display(ascending.head())

# 2. Sort by sepal length in descending order
print("\n2. Sepal Length - Descending Order:")
descending = df.sort_values(by="sepal_length", ascending=False)
display(descending.head())

# 3. Sort by petal length in ascending order
print("\n3. Petal Length - Ascending Order:")
display(df.sort_values(by="petal_length", ascending=True).head())

# 4. Sort by multiple columns
print("\n4. Sort by Species and Sepal Length:")
multiple_sort = df.sort_values(
    by=["species", "sepal_length"],
    ascending=[True, False]
)
display(multiple_sort.head(10))

print("\nDataset sorting completed successfully!")

Original Dataset:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

1. Sepal Length - Ascending Order:

    sepal_length  sepal_width  petal_length  petal_width species
13           4.3          3.0           1.1          0.1  setosa
8            4.4          2.9           1.4          0.2  setosa
42           4.4          3.2           1.3          0.2  setosa
38           4.4          3.0           1.3          0.2  setosa
41           4.5          2.3           1.3          0.3  setosa

2. Sepal Length - Descending Order:

     sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica

3. Petal Length - Ascending Order:

    sepal_length  sepal_width  petal_length  petal_width species
22           4.6          3.6           1.0          0.2  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
16           5.4          3.9           1.3          0.4  setosa

4. Sort by Species and Sepal Length:

    sepal_length  sepal_width  petal_length  petal_width species
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
18           5.7          3.8           1.7          0.3  setosa
33           5.5          4.2           1.4          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
16           5.4          3.9           1.3          0.4  setosa
20           5.4          3.4           1.7          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa

Dataset sorting completed successfully!